apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: ${{ values.appName }}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    sonarqube.org/project-key: Staffing-HQ_${{values.component_id}}
  tags:
    - spring-boot
    - java
    - maven
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  providesApis:
    - ${{ values.component_id }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-api
  title: ${{ values.appName }} API
  description: REST API for the ${{ values.appName }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  definition:
    $text: ./openapi.yaml
