{%- set owners = values.owners %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: ${{ values.appName }}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    {%- if values.cicd === true %}
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    {%- endif %}
    {%- if values.sonarqube === true %}
    sonarqube.org/project-key: ${{ values.sonarqubeProjectKey }}
    {%- endif %}
    {%- if values.kubernetes === true %}
    backstage.io/kubernetes-id: ${{ values.k8sId }}
    backstage.io/kubernetes-namespace: ${{ values.k8sNamespace }}
    backstage.io/kubernetes-label-selector: 'app=${{ values.podLabel }}'
    {%- endif %}
    {%- if values.grafana === true %}
    grafana/overview-dashboard: ${{ values.grafanaDashboardUrl}}
    grafana/dashboard-selector: ${{ values.grafanaDashboardSelector}}
    grafana/tag-selector: 'app=${{ values.grafanaDashboardSelector }}'
    {%- endif %}
  tags:
    - spring-boot
    - java
    - maven
spec:
  type: service
  owner: 
    {%- for owner in owners %}
    - '${{ owner }}'
    {%- endfor %}
  lifecycle: experimental
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  {%- if values.dependsOn %}
  {%- set dependencies = values.dependsOn %}
  dependsOn:
    {%- for dependency in dependencies %}
    - '${{ dependency }}'
    {%- endfor %}
  {%- endif %}
  providesApis:
    - 'api:default/${{ values.component_id }}-api'

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-api
  title: ${{ values.appName }} API
  description: REST API for the ${{ values.appName }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  dependsOn:
    - component:default/${{ values.component_id }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  definition:
    $text: ./openapi.yaml
