apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  title: ${{values.appName}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  links:
    - url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      title: Website
      icon: dashboard
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
  tags:
    - nextjs
    - react
    - ssr
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner}}
