apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.system | dump}}
  dependsOn:
    - ${{values.component_id}}-db
  definition:
    $text: ./openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.component_id}}-db
spec:
  type: database
  owner: ${{values.owner | dump}}
  system: ${{values.system | dump}}