apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  title: ${{values.title | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
      github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
      backstage.io/techdocs-ref: dir:.
  tags:
    - fastapi
    - python
    - openapi
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system}}
  providesApis:
    - ${{values.component_id}}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}-api
  title: ${{values.title}} API
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system}}
  definition:
    $text: ./openapi.yaml
