apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-fast-api
  title: Create a Python FastAPI app
  description: A template for creating a Python FastAPI app
  tags:
    - python
    - fastapi
    - openapi
spec:
  owner: group:developers
  type: service

  parameters:
    - title: Basic information for the FastApi app
      required:
        - component_id
        - title
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        title:
          title: Title
          type: string
          description: A short title of the component
        description:
          title: Description
          type: string
          description: A short description of the component
    - title: Configure component relationships
      required:
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: The owner of the component
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        dependsOn:
          title: Depends on
          type: array
          description: The component that this component depends on
          ui:field: MultiEntityPicker
          ui:options:
            catalogFilter:
              - kind: [Component, API, Resource]
        system:
          title: System
          type: string
          description: The system that the component belongs to
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
    - title: Configure plugins
      properties:
        enableSonarQube:
          title: SonarQube
          type: boolean
          default: false
        enableGrafana:
          title: Grafana
          type: boolean
          default: false
        enableCICD:
          title: CI/CD
          type: boolean
          default: false
        enableKubernetes:
          title: Kubernetes
          type: boolean
          default: false
      dependencies:
        enableSonarQube:
          allOf:
            - if:
                properties:
                  enableSonarQube:
                    const: true
              then:
                required:
                  - sonarqubeProjectKey
                properties:
                  sonarqubeProjectKey:
                    title: Project key
                    description: SonarQube project key
                    type: string
        enableGrafana:
          allOf:
            - if:
                properties:
                  enableGrafana:
                    const: true
              then:
                required:
                  - grafanaDashboardUrl
                  - grafanaDashboardSelector
                properties:
                  grafanaDashboardUrl:
                    title: Grafana dashboard URL
                    type: string
                    format: uri
                  grafanaDashboardSelector:
                    title: Grafana dashboard selector
                    type: string
        enableKubernetes:
          allOf:
            - if:
                properties:
                  enableKubernetes:
                    const: true
              then:
                required:
                  - k8sId
                  - podLabel
                  - k8sNamespace
                properties:
                  k8sId:
                    title: Kubernetes identifier
                    type: string
                  podLabel:
                    title: Kubernetes Pod label
                    type: string
                  k8sNamespace:
                    title: Kubernetes namespace
                    type: string
                    default: default
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        copyWithoutTemplating:
          - .github/workflows/*.yml
          - .github/workflows/*.yaml
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          dependsOn: ${{ parameters.dependsOn }}
          title: ${{ parameters.title }}
          sonarqube: ${{ parameters.enableSonarQube }}
          sonarqubeProjectKey: ${{ parameters.sonarqubeProjectKey }}
          grafana: ${{ parameters.enableGrafana }}
          grafanaDashboardUrl: ${{ parameters.grafanaDashboardUrl }}
          grafanaDashboardSelector: ${{ parameters.grafanaDashboardSelector }}
          cicd: ${{ parameters.enableCICD }}
          kubernetes: ${{ parameters.enableKubernetes }}
          k8sId: ${{ parameters.k8sId }}
          podLabel: ${{ parameters.podLabel }}
          k8sNamespace: ${{ parameters.k8sNamespace }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  # Outputs are displayed to the user after a successful execution of the template
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
